import { Inter } from 'next/font/google';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';

import './globals.css';
import NavBar from './(components)/NavBar';

config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Ticket',
  description: 'Generated by Arik Alexandrov',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex flex-col h-screen max-h-screen'>
        <NavBar/>
          <div className='flex-grow overflow-y-auto bg-page text-default-text'>
            { children}
          </div>
        </div>
      </body>
    </html>
  )
}
